### ISSUE TITLE
Move onboard simulation scripts to the landside simulation package

### ISSUE THREAD

**Issue by muthuArivoli** [DukeRobotics/robosub-ros#235]
## To-do
- [x] Move `simulation_republisher.py` from sensor fusion package to simulation package
- [x] Create script for republishing sim control Float messages to offboard comms style ThrusterSpeeds messages (can also add this to the simulation republisher script from above)
- [x] Fix all launch files and readmes (add this script to the basic launch file in simulation and delete it from the onboard launch files)

## Background
Simulation was refactored into its own ROS package as part of #222. Thus, as part of the general effort of switching from our previous workspace structure, to the current divide of onboard and landside, we should try to move the simulation stuff into landside. This will make the controls code simpler, since they don't need to publish two different message types based on the conditional argument. Also, the simulation republisher script should really be located in the simulation package and not in the sensor fusion package.

The only simulation stuff that should remain in the onboard workspace should be the PID constants for simulation, since there doesn't seem to be a good way to keep those in the landside workspace, and load it into the control package. Thus, I think it is fine for the constants (and data in general) to be stored in onboard, but all scripts should be located in simulation.
