### ISSUE TITLE
Python Simulation Rewrite

### ISSUE THREAD

**Issue by muthuArivoli** [DukeRobotics/robosub-ros#275]
## Background
Our simulation code is in Lua, which no one knows, and according to linters like LuaCheck is simply not well written. We also currently require devs to run a script on their own machine and then use CoppeliaSim to run a model inside the container with the actual robot model outside of the container, echoing the data as in: `robot model (CoppeliaSim) -> ros_coppelia_comm.py -> cuboid model (CoppeliaSim) -> ROS`. We can cut this down by using the communcation model `robot model (CoppeliaSim) -> ROS` which combines the ros_coppelia_comm and ROS driver, and runs them both inside the container.

To do this, we can use the RemoteAPI for Python for CoppeliaSim, and add standard ROS code to publish and subscribe to relevant data. This data will then be sent to the simulation via the RemoteAPI. The only Lua code that should exist are bindings for functions that exist in the RegularAPI, but not in the RemoteAPI, and these should be as simple as calling a single function, or simply assigning data. These Lua functions can then be called from the Python code using the CallScriptFunction in the RemoteAPI.

This closes and supersedes #232.

## Tasks

- [ ] Design structure of Python package (event loop/CoppeliaSimClient)
- [ ] Write Lua bindings for functions that exist only in the RegularAPI
- [ ] Port sensor code (simulation publishing data)
- [ ] Port movement code (simulation receiving data)
- [ ] Determine IP address of container on Macs (and document on Windows, its at `/etc/resolv.conf`)
