### ISSUE TITLE
Finalize GUI for robot testing/control

### ISSUE THREAD

**Issue by AndrewCouncil** [DukeRobotics/robosub-ros#301]
## Background
Using a GUI to interface with the robot instead of a series of terminal windows has obvious time and ease of use advantages. The bulk of the work is done, but a few components need to be finalized before implementation. 

## Task
A few parts have further work required:
- [ ] Fix the sizing of buttons on the UI file to match the possible text displayed
- [ ] Create a checkbox for simulation mode in the UI file and add to module file, which will change commands run for use in simulation testing
- [ ] Get working publishing of twists/poses through publisher in module file instead of current nonfunctional SSH method
- [ ] Make method to start motion.launch file
We have attempted to use paramiko to create an SSH terminal to start a launch file by creating a paramiko channel for the launch file to be run in the background, but this was not functional. Will either need to find the correct way to run it over SSH or complete #292 .
