### ISSUE TITLE
Measure Cthulhu's velocities

### ISSUE THREAD

**Issue by ShaanGondalia** [DukeRobotics/robosub-ros#321]
## Background

The PID loops contain many magic values that were set arbitrarily when they were first written. Most of these values are directly related to the kinematics of our robot, such as max linear and angular velocity. These robot constants will be measured at the pool and the PID launch files will be updated accordingly. See [Controls Refactoring](https://github.com/DukeRobotics/robosub-ros/blob/controls-refactoring/onboard/catkin_ws/src/controls/launch/position_pid.launch) for specific TODOs.

## Tasks

- [ ] Measure maximum lateral velocities (x, y, z)
  - [ ] Update control effort range for position PID loops
  - [ ] Make sure max speed in simulation matches real max speed
- [ ] Measure maximum angular velocities (roll, pitch, yaw)
  - [ ] Determine maximum orientation control effort in position and velocity PID loops
  - [ ] Determine units of measurement
- [ ] Explore other PID loop constants, such as windup limit and cutoff frequency

**Comment by vedarshshah** [comment]
This does not seem to be necessary as we map the min/max PID outputs to min/max thruster speeds, which are mapped by the Arduino to min/max ESC PWMs, which result in the min/max thruster speeds. Thus, it does not really matter what the min/max values are for the PID output, so we can just keep them as is.
