### ISSUE TITLE
Integrate Thruster Power Curve & Change Thruster Arduino Comms

### ISSUE THREAD

**Issue by ShaanGondalia** [DukeRobotics/robosub-ros#324]
# Background

The current controls algorithm assumes thruster force scales linearly with power applied. The actual T200 power curve is provided by Blue Robotics [here](https://bluerobotics.com/store/thrusters/t100-t200-thrusters/t200-thruster-r2-rp/). The controls algorithm should factor in this data to determine the actual 8-bit power value to send to each thruster.

An important note here is that the thrust applied is not symmetric for reverse and forward PWM input values. We need to come up with an algorithm that handles this. This is especially important because some of our thrusters are "reversed", so an expect forward movement actually requires a PWM input in the "reverse" range.

Additionally, the thruster Arduino frequently disconnects as it runs ROS. The communication method needs to be changed so the connection is reliable.

# Purpose
Integrate the nonlinear thruster power curve and improve reliability of connection between robot and thruster Arduino.

# Tasks
- [x] Change controls to publish floats between [-1, 1] to `controls/thruster_allocs` instead of publishing 8-bit integers to `offboard/thruster_speeds`. 
- [x] Develop a node in `offboard_comms` that subscribes to `controls/thruster_allocs` and converts thruster allocs to pulse widths, taking into account the current voltage.
- [x] Modify thruster Arduino code to accept PWMs from the aforementioned node instead of 8-bit integers.
