### ISSUE TITLE
Add task planning and cv dependencies

### ISSUE THREAD

**Issue by ShaanGondalia** [DukeRobotics/robosub-ros#331]
## Background

We need to add certain dependencies to our Dockerfiles for task planning and computer vision.

## Tasks
- [x] Add depthai library
- [x] Add smach library
- [x] Uncomment corresponding nodes in [`stream_images.launch`](https://github.com/DukeRobotics/robosub-ros/blob/master/onboard/catkin_ws/src/cv/launch/stream_images.launch) and [`task_runner.launch`](https://github.com/DukeRobotics/robosub-ros/blob/master/onboard/catkin_ws/src/task_planning/launch/task_runner.launch)
