### ISSUE TITLE
Enable basic movement via smach

### ISSUE THREAD

**Issue by ShaanGondalia** [DukeRobotics/robosub-ros#332]
## Background

In efforts to keep smach progress incremental and digestible, we are splitting task planning issues into smaller chunks. This should improve our testing process and ensure that the task planning framework works as expected on both the robot and in simulation. We should test basic movement using local and global position and velocity control. Once this functionality is verified, we should use a state machine to chain these basic movements together (this should be incredibly easy if smach is implemented correctly).

## Important notes

When testing, we should keep dependencies on controls as limited as possible so we don't waste time tuning PID constants when we should be testing framework functionality. We should mainly check that tasks are started correctly and end conditions are met as expected, without regard to how the robot got there.

## Tasks
- [x] Get `task_runner.py` and `task_runner.launch` functional
- [x] Use `task_runner.launch` to test isolated tasks in simulation. 
  - [x] Global position task
  - [x] Local position task
  - [x] Local velocity task
- [x] Test framework on robot
  - [x] Global position task
  - [x] Local position task
  - [x] Local velocity task
  - [x] Combine tasks sequentially to move in a square.
