### ISSUE TITLE
Add Scripts for OAK Camera

### ISSUE THREAD

**Issue by tylerfeldman321** [DukeRobotics/robosub-ros#342]
## Background
The cv package is not up-to-date with the work done with the OAK-D PoE camera over the 2022 competition. Currently master has a single incomplete and undocumented script for the OAK camera using the depthai package. Since we are sticking with the OAK cameras for stereo vision (as an alternative to mono cameras + sonar), we should add important scripts to test the cameras and run spatial detection.

## Tasks
- [x] Add script and launch file for spatial detection using OAK camera
- [x] Add .yaml file to specify models to use for spatial detection with the OAK camera
- [x] Add script and launch file for streaming and publishing RGB camera feed from the OAK camera
- [x] Add documentation to scripts and cv package README to reflect changes
- [x] DepthAI package is already added to dependencies in #335 
- [x] Remove `stream_images.py` handled by #341

**Comment by tylerfeldman321** [comment]
Depthai scripts and documentation have been added to the cv-depthai branch.
