### ISSUE TITLE
Get New Mono Cameras Working

### ISSUE THREAD

**Issue by tylerfeldman321** [DukeRobotics/robosub-ros#346]
## Background
We are using the [exploreHD 2.0 Underwater Subsea ROV/AUV USB Camera](https://exploredeepwater.com/products/explorehd-rov-auv-usb-camera) for mono vision, to use as our downward facing camera, and potentially use as our frontward facing camera (but are planning for the OAK as of now). We will create a ROS node to publish the raw feed from these cameras so our detection script can be used on the camera feed.

## Tasks
- [ ] Create node in CV package to publish the raw camera feed to a topic
    - [ ] Script for publishing raw camera feed
    - [ ] Launch file
    - [ ] Use image_view to verify the camera feed is correct
- [ ] Run detection.py on the camera feed above land using the camera feed
- [ ] Waterproof the connectors to the camera
- [ ] Test the cameras underwater
    - [ ] Check that the camera feed is working and looks reasonable
    - [ ] Run detections underwater using the camera feed
