### ISSUE TITLE
Improve Functionality and Model Flexibility for Object Detection

### ISSUE THREAD

**Issue by tylerfeldman321** [DukeRobotics/robosub-ros#347]
## Background
For the past few years, we have been using [detecto](https://detecto.readthedocs.io/en/latest/) for model training and inference for our allied vision / mako cameras. This package allows us to use minimal amounts of code for model training and inference, but lacks in some functionality like non-max suppression, object detection metrics like mAP (mean average precision), and does not allow for flexibility in what model we want (detecto only supports three models: fasterrcnn_resnet50_fpn, fasterrcnn_mobilenet_v3_large_fpn, and fasterrcnn_modbilenet_v3_large_320_fpn). We'd like to transition to a different PyTorch wrapper and/or develop our own package to allow for model flexibility and extended functionality.

## Tasks
- [ ] Research alternate PyTorch wrappers for object detection that allow for model flexibility
- [ ] Choose between using any PyTorch wrappers we found, writing our own package, or potentially making a PR to detecto's source code
- [ ] Complete whatever was chosen. Will update this issue with tasks once we decide what to do

**Comment by vedarshshah** [comment]
We have decided to use the stereo camera as our primary front facing camera. Additionally, we will not have the time to use a downward-facing mono camera to detect path markers or other objects. Therefore, we have prioritized improving our DepthAI object detection and moving to another PyTorch wrapper is not worth the effort. We will consider this again if and when we decide to perform detections on the mono camera.
