### ISSUE TITLE
Setup and Test New OAK Camera

### ISSUE THREAD

**Issue by tylerfeldman321** [DukeRobotics/robosub-ros#348]
## Background
We have ordered the [OAK-D W PoE](https://docs.luxonis.com/projects/hardware/en/latest/pages/NG9097w.html) as a front facing stereo camera option for the robot. We would like to test spatial detections above land, then waterproof and place in the BlueRobotics enclosure we purchased, and calibrate the camera for underwater use.

## Tasks
- [x] Once camera arrives, get local testing working by visualizing the RGB and depth map camera feed
- [x] Use code from competition to verify that spatial detection is working on land
- [x] Waterproofing + fit into BlueRobotics enclosure
- [ ] Calibrate stereo camera for underwater use
- [ ] Enhancements
    - [ ] Tune stereo vision settings for best performance
    - [ ] Replace object detection with object tracking
- [ ] Update for DepthAI v3 if needed

**Comment by vedarshshah** [comment]
Recalibration of stereo camera is unnecessary as we will be using sonar to obtain depth information. Will explore replacing object detection with object tracking in Spring 2023.
