### ISSUE TITLE
Sonar Package

### ISSUE THREAD

**Issue by tylerfeldman321** [DukeRobotics/robosub-ros#349]
## Background
We'd like to create a ros node for the [BlueRobotics Ping360](https://bluerobotics.com/store/sensors-sonars-cameras/sonar/ping360-sonar-r1-rp/) device so that sonar data can be received and provided to other nodes.

## Tasks
- [x] Get sonar working locally with Pingviewer
- [x] Basic script to request and print data received from the sonar device
- [x] Create sonar ros package
- [x] Add dependency on bluerobotics-ping to the sonar package
    - [x] Update package.xml
    - [x] Update Dockerfile for onboard
- [x] Test dependency on bluerobotics-ping
- [x] Test sonar device underwater
- [x] Create script with Sonar class to interface with the device
- [x] Decide on how sonar data should be published or how other ros nodes will interact with the sonar node

**Comment by tylerfeldman321** [comment]
Should this be its own package?
