### ISSUE TITLE
CV Sprint 1 Monovision: Raw Image Node and Detecto Changes

### ISSUE THREAD

**Issue by ricohasgithub** [DukeRobotics/robosub-ros#352]
### Background
Although we don't fully know which cameras we will use yet (need to see how well stereo cameras are waterproofed), these tasks for CV will be useful regardless of whether we stick with the monovision cameras. Our main tasks are to create a raw image publishing node and to look at implementing/testing the monovision code without Detecto (by using a different library, or just Pytorch .etc). We will need to have some sort of raw image stream set up to make testing easier regardless of which camera we choose. We also want to have more flexibility/control over what models we deploy to the bot, and our current detection script using Detecto is limited in that regard.
### Tasks
- [x] Create `raw_image_publisher` class in a new script (say `raw_image_publisher.py`) which feeds the CV bridge image stream directly to a rostopic
- [ ] Research alternatives to Detecto without going directly to pure Pytorch. We want to avoid using Pytorch directly if possible since that will involve a lot of maintenance (as Pytorch is always being updated), but we definitely could resort to that if we cannot find a reasonable alternative. We should decide on this by October 3rd
- [ ] Re-implement `detection.py` in the package we choose to use once we decide

**Comment by ricohasgithub** [comment]
- Created a new script that allows for live streaming from a mono camera bridge to cv2, tests pending
- Decided that migrating from detecto will be a future project
