### ISSUE TITLE
CV Sprint 1 Stereovision: Understanding DepthAI

### ISSUE THREAD

**Issue by vedarshshah** [DukeRobotics/robosub-ros#353]
### Understanding DepthAI

Programming the Luxonis stereo vision cameras requires a solid understanding of DepthAI. New CV members have not seen DepthAI yet. So, they must first learn DepthAI and well enough to comprehend our current DepthAI code before they can start working on DepthAI projects. They must also complete the appropriate setup on their computers to ensure they can test DepthAI code locally.

## Tasks

The main objective for new members will be to understand DepthAI by reading the documentation and our current DepthAI code. To solidify their understanding, they will build a flowchart of our current DepthAI spatial detection pipeline. Vedarsh will walk them through all setup required to ensure they can connect to the  DepthAI camera inside the robosub-ros Docker container for local testing. 

- [x] Connect to the Luxonis OAK camera from inside the Docker container from laptop.
- [x] Understand current DepthAI code.
- [x] Build flowchart of DepthAI spatial detection pipeline.

Update Oct 8 - As new members have grasped DepthAI earlier than expected, they began completing tasks that build towards the CV control panel. These tasks are described in the issue for Sprint 2.

**Comment by vedarshshah** [comment]
CV Sprint 1 Stereovision tasks completed. Tasks related to the CV control panel have moved to #358.
