### ISSUE TITLE
CV Sprint 3: Short and Tidy

### ISSUE THREAD

**Issue by vedarshshah** [DukeRobotics/robosub-ros#374]
## Purpose

The primary intent of this sprint is to tie the loose ends from sprint 2 and get ready for the pool test on November 12. As a result, this sprint includes an assortment of short, but important, tasks.

## Meetings Covered

- Wednesday, November 2
- Saturday, November 5
- Wednesday, November 9
- Saturday, November 12 (Pool Test)

Note: this sprint is shorter than the usual sprint length of 2 weeks.

## Tasks

- [x] Write script that connects to DepthAI camera with an input to switch between robot and local connection and to automatically try again a few times with a time delay if connection fails.
- [x] Modify all DepthAI scripts to use DepthAI connection script to connect to DepthAI camera instead of connecting directly to camera, passing two arguments: pipeline, and robot vs local.
- [x] Parametrize the default package of CVLaunchPlugin.
- [x] Modify depthai_publish_image_streams.py to additionally publish stereo.depth.
- [x] Add documentation for changes made in Sprint 2.
    - [x] Simulated Image Streams
- [x] Test if footage_extraction.py works with commented out import.
- [x] Determine workflow for visualizing bag files captured through rqt_bag.
- [x] Merge `cv-depthai`, `cv-simulated-image-feeds`, and `cv-control-panel` into `cv`.

**Comment by vedarshshah** [comment]
Completed Sprint 3. Open tasks moved to Sprint 4 (#381).
