### ISSUE TITLE
Swap to Nano RP2040 Connect

### ISSUE THREAD

**Issue by ShaanGondalia** [DukeRobotics/robosub-ros#375]
## Background
We will eventually need to swap to a micro-controller with more storage as a part of #350. The [Arduino Nano RP2040 Connect](https://docs.arduino.cc/hardware/nano-rp2040-connect) has the same footprint as the Nano Every that we currently use, which will allow us to migrate without having to change the layout of our electrical stacks. We can replace the Nano Every while still running ROS1, which will save us time later and help us identify any potential issues with the upgrade. We should first create a test rig to check that everything works as expected.  Once we're able to verify connections to the pressure sensor and PWM multiplexer, we can put them on Cthulhu.

## Tasks
- [ ] Create test rig with Nano RP2040 Connect, PWM multiplexer, and pressure sensor. We should keep this test rig around so that we can test the ROS2 migration as part of #350.
- [ ] Update [`arduino_upload.sh`](https://github.com/DukeRobotics/robosub-ros/blob/master/onboard/catkin_ws/src/offboard_comms/scripts/arduino_upload.sh) with the correct controller specs
- [ ] Replace the Nano Every in each robot with a Nano RP2040 Connect.

**Comment by vedarshshah** [comment]
We've completed ROS2 migration in `robosub-ros2`; we don't need to switch to a different Arduino.
