### ISSUE TITLE
CV Sprint 4: Object Detection

### ISSUE THREAD

**Issue by ricohasgithub** [DukeRobotics/robosub-ros#381]
## Purpose
The past 3 sprints have mainly dealt with setting up our camera, visualizing it, and getting it to publish to a ros-topic. This sprint will build on what we've done so far to enable object detection both the stereo and mono cameras and complete the CV fall semester goals. We plan to test object detection in a pool test on December 3 and merge all changes made this semester into `master` before the end of the semester. This will be the last sprint of fall semester.

## Meetings Covered
- Wednesday, November 16
- Saturday, November 19
- Wednesday, November 30
- Saturday, December 3 (Pool Test)
- Wednesday, December 7

## Tasks
- [x] Publish RGB feed from mono camera to topic.
- [x] Ensure object detection works on mono camera using `detection.py` and existing models.
- [x] Ensure object detection works on stereo camera using `depthai_spatial_detection.py` and existing models.
- [x] Separate System Usage widget into its own file.
- [x] Add System Usage widget to CV Launch widget.
- [x] Replace Systems Widget with CV Launch widget and drop CV moniker.
- [x] Add packages rqt-bag and rqt-image-view to Docker build.
- [x] Add documentation for DepthAI and control panel.
- [x] Test `test_images.py`.
- [x] Test wireless connectivity of old robot.
- [x] Setup flake8 linter in VSCode (everyone).

### Optional
- [x] Develop custom rosbag widget.
- [x] Develop method to run multiple DepthAI scripts simultaneously.
- [x] Visualize stereo RGB stream with bounding boxes overlaid when object detection is on.
- [x] Add ability to launch rosservice calls through launch widget.
- [x] Complete `depthai_simulate_spatial_detection.py`

**Comment by vedarshshah** [comment]
Completed Sprint 4.
