### ISSUE TITLE
Camera Status RQT Plugin

### ISSUE THREAD

**Issue by vedarshshah** [DukeRobotics/robosub-ros#391]
# Background

It is important for CV to know whether the stereo and mono cameras are connected. Currently, there is no way to do this using the CV GUI. Current methods to get the cameras' status relies on scripts that are not designed for this purpose and relies on terminal and/or rosout output. Since we want to be able to perform all important CV activities on the robot using just the CV GUI, we need to develop a script that obtains the camera statuses and develop an RQT plugin to display the camera status.

# Purpose

Develop a script to obtain the ping and connection statuses of DepthAI and mono cameras that publishes these statuses to a rostopic. Develop an RQT plugin to display the cameras' status and integrate it into the CV GUI.

# Tasks
- [x] Develop a script to obtain the cameras' status on onboard.
   - [x] Develop a service to ping DepthAI camera. Publish a `diagnostic_msg` each time a ping is performed. 
   - [x] Develop a service to attempt to connect to DepthAI camera using `depthai_camera_connection.py`. Calls the connection method only _once_ and publishes a `diagnostic_msg`.
   - [x] Develop a service to attempt to get frames from the mono camera using `cv2.VideoCapture`. Repeatedly attempt to get successfully get a frame for 5 seconds. Publish a `diagnostic_msg` when successful or when timeout.
- [x] Develop an RQT plugin to display the cameras' status.
   - [x] Initialize the plugin.
   - [x] Design the UI for the plugin using Qt Designer.
   - [x] Develop onclick actions for the buttons to start/stop ping, test DepthAI connection, and test mono connection that call the appropriate services.
   - [x] Subscribe to the topic `/camera_status` and use the messages that are published on that topic to update the statuses displayed.
   - [x] Modify the CV GUI perspective file to incorporate the plugin.
   - [x] Fix issue with subscribers in camera status plugin and system usage plugin not connecting when the subscribed-to topic is published to after the GUI is launched.
   - [x] Display ping message when the user double clicks on a row in the ping log.
   - [x] Add a help dialog (triggered by ? icon in toolbar) that provides information on how the plugin works.
   - [x] Add a configuration dialog to change the ping hostname, usb camera channel, and to restart the ping subscriber.
