### ISSUE TITLE
RQT Fixes

### ISSUE THREAD

**Issue by vedarshshah** [DukeRobotics/robosub-ros#392]
# Purpose

Make a number of minor fixes and improvements to various RQT plugins.

# Tasks

- [x] Remove libGL errors that show up every time RQT is loaded.
- [x] Separate the System Usage widget into its own plugin.
- [x] Reduce the horizontal space taken by the System Usage widget.
- [x] Add a separator between launch files and Python files in the node selection dropdown of Launch Dialog.
- [x] Add help tooltips to arguments in Launch Dialog.
- [x] Add type checking to arguments in Launch Dialog.
- [x] Add regex checking to arguments in Launch Dialog.
- [x] Use checkboxes instead of text fields for boolean arguments in Launch Dialog.
- [x] Use combo boxes instead of text fields for arguments with a predefined list of possible values in Launch Dialog.
- [x] Remove QStandardPaths error that shows up every time RQT is loaded.
- [x] Add empty checking to arguments in Launch Dialog.
