### ISSUE TITLE
Object Tracking

### ISSUE THREAD

**Issue by vedarshshah** [DukeRobotics/robosub-ros#394]
# Background

Currently, our DepthAI object detection pipeline produces detections at 1Hz. The RGB camera has a frame rate of 60FPS. Clearly, there significant is room for improvement in our detection rate. Object detection works by taking a frame as a still image and passing it through a computationally expensive neural network to produce bounding boxes. Performing object detection on every frame is impossible due to the high computational expense. However, we can instead leverage object tracking in conjunction with object detection to produce detections with a much lower computational expense, and thus improve the detection rate.

Object tracking leverages the temporal nature of a live video feed. The time elapsed between frames is just 1/60th of a second. Therefore, for any given frame, we can safely assume the types of objects in the frame will be the same as in the next few frames. And, the locations of the objects will also be nearly the same, with only minor changes. Therefore, we can perform object detection on one frame to get types and locations (bounding boxes) of objects, then use object tracking to simply update the bounding boxes for the next few frames using a much less computationally expensive algorithm, and repeat the cycle. This should enable us to detect at a much faster rate than we can currently (perhaps 15Hz).

# Purpose

Integrate object tracking into our current DepthAI spatial detection pipeline and measure the resulting change in performance (speed & accuracy).

# Tasks
- [ ] Determine the highest detection rate we can achieve on the robot with our current pipeline (without object tracking). This enables us to obtain a baseline speed against which we can compare the speed of object tracking after it's implemented. To do this, change or remove the loop_rate in `depthai_spatial_detection.py` or `depthai_simulate_detection.py` (depending on if you are using a live or simulated camera feed) and test object detection.
   - Simulated detection rate: 5.6 Hz on @vedarshshah's computer, 9 Hz on @gummydumpling-2001's computer
- [ ] Implement object tracking in `depthai_spatial_detection.py` and `depthai_simulate_detection.py`. Start [here](https://docs.luxonis.com/projects/api/en/latest/components/nodes/object_tracker/) for guidance. Click on the links in the "Examples of Functionality" section to see examples of object tracking implemented with spatial detection and object detection.
- [ ] Measure the detection rate we can achieve on the robot with object tracking and compare this against the baseline detection rate to determine the improvement. Also, compare accuracy qualitatively on simulated and live feeds.

**Comment by vedarshshah** [comment]
We discovered that object tracking was actually slower than object detection and provided less accurate results. Additionally, we discovered ways to improve the detection rate with object detection, so object tracking is no longer needed.
