### ISSUE TITLE
Transition to Compressed Images

### ISSUE THREAD

**Issue by vedarshshah** [DukeRobotics/robosub-ros#395]
# Background

All CV code in this repo uses the raw `Image` format when publishing images to topics. This uses a lot of memory, especially for images with large resolutions, and can lead to a slowdown of the entire ROS system. To mitigate this issue, instead of using the raw `Image` format, we need to switch over to the `CompressedImage` format which uses less memory to publish images.

There is two wrinkles in this transition. All bag files that have been recorded in the past use the raw `Image` format. Thus, to play a bag file recorded before this transition and subscribe to the images published by the bag file from our scripts, the scripts must use the raw `Image` format in that case. Therefore, scripts that subscribe to a topic with images must be able to detect whether the images are raw or compressed and handle them accordingly.

The other wrinkle is that, RQT ImageView does not display compressed images unless the topics to which they are published end with `/compressed`. For example, compressed images published to the topic `/camera/front/rgb` cannot be displayed by ImageView unless the topic is changed to `/camera/front/rgb/compressed`.  Therefore, all image topic names will also have to be changed to include `/compressed` at the end so they are compatible with ImageView.

# Purpose

First, transition all topicTransition all CV code that publishes images to a topic to use the `CompressedImage` format instead of the raw `Image` format and add `/compressed` to the end of the topic name. Additionally, enable all CV code that subscribes to topics with images to detect the image type (raw or compressed) and handle it accordingly.

Note that the most challenging part of this transition is not the transition itself, but rather the testing required to ensure all changed code works. Since this transition affects many scripts, each in multiple parts, all affected parts of all scripts must be tested to make sure they work properly. Since each script and part requires different data and methods to test it thoroughly, the task of testing everything will be challenging.

# Tasks
- [x] Copy & paste the `ImageTools` class from `image_tools.py` under cv/footage_extraction into `utils.py` under cv/scripts. Do not copy the `__main__` function at the bottom. This class provides functions to convert images between each of the three formats: `cv2`, raw `Image`, and `CompressedImage`. Look through the functions in this class so you know what is available. Use the generic functions `convert_to_cv2`, `convert_to_ros_msg` and `convert_to_ros_compressed_msg` when possible. Do not use any other functions, libraries, classes, etc (such as `CvBridge`) to perform conversions between the types; use `ImageTools` only. This class will be the backbone of the transition.
- [x] Transition all publishers in the following files to use the `CompressedImage` format and have `/compressed` at the end of their topic names. For scripts where the topic name is a user-provided argument, do not change it (assume the user will add `/compressed` at the end). Use the function created in the first task to convert images to the `CompressedImage` format. **Transition one file at a time and test each one to make sure it works correctly before proceeding to the next file.** The files are listed in ascending order by transition difficulty.
   - [x] `usb_camera.py`
   - [x] `depthai_simulate_detection.py`
   - [x] `test_images.py`
   - [x] `depthai_spatial_detection.py`
   - [x] `depthai_publish_image_stream.py` **In this file, talk to @vedarshshah before changing the conversion of the left and right mono camera images, as well as the depth image as it requires a different procedure.**
- [x] Enable all subscribers in the following files to handle raw and compressed image types. Typically, when a subscriber is instantiated, we specify the message type that is being published to the topic we are subscribing to. In this case, however, we are not sure what the message type is; it could be the raw `Image` or `CompressedImage`. Therefore, we must programmatically obtain the message type being published to the topic and use this type in the subscriber. See the **bottommost answer** in [this Stack Overflow post](https://stackoverflow.com/questions/69286639/get-ros-message-type-at-runtime) for an example on how to do that. In the subscriber callback function, to convert the message to `cv2`, use the generic functions mentioned in the first task above. These functions will automatically detect if the message is raw or compressed and handle it accordingly. **Transition one file at a time and test each one to make sure it works correctly before proceeding to the next file.** Both files are equally easy to transition.
   - [x] `depthai_simulate_detection.py`
   - [x] `detection.py`

**Comment by maxwellmlin** [comment]
Need to install image-transport-plugins on landside to view compressed images on the cv_gui
```apt install ros-${ROS_DISTRO}-image-transport-plugins```

https://answers.ros.org/question/270881/unable-to-load-plugin-for-transport-image_transportcompressed_sub/

**Comment by vedarshshah** [comment]
> I needed to install image-transport-plugins on landside to view compressed images on the cv_gui `apt install ros-${ROS_DISTRO}-image-transport-plugins`
> 
> https://answers.ros.org/question/270881/unable-to-load-plugin-for-transport-image_transportcompressed_sub/

The install has been added to the core Dockerfile.
