### ISSUE TITLE
Sonar Fixes 

### ISSUE THREAD

**Issue by Will-Denton** [DukeRobotics/robosub-ros#400]
# Background

The sonar uses the blue robotics ping-360 library to interact with the physical sonar device, however, the sonar code which we use to connect to the sonar has a few issues. The original system which we developed to communicate with the sonar through ros actions was too slow for the quick sonar pings which we need for sonar-CV integration. Now we are switching to the usual rosnode system but there are lots of artifacts currently within the code base. 

The current sonar code is functional but it needs changes before it is ready to be marked as its own package.

# Purpose

These changes will make the sonar system more robust as currently there are a few problems which will hinder the modularity of the system. In the sonar setup, the sonar is currently found through a hardcoded port. This is a problem as the same code will not work on multiple robots or within a different system. The 'SERIAL_PORT_NAME' should be changed to be found through an automated system similar to 'imu.py'. 

The sonar does not run off of a range, rather it has a 'duration', 'number of samples', and 'period' which it uses to get sonar data over a range of points. The duration is the length of one ping and the period is how often the sonar pings. These two together control the effective range of the sonar. The number of samples is the number of pings used throughout the range determined by the other two parameters. Lowering this will make the sonar faster but more granular. The current way these parameters are calculated is through a linear function, however, they should be changed to match the original code in the pingviewer application made by bluerobotics. 

The data we get from the sonar is stored in an array where the columns are the number of samples and the rows are the angles. Visualizing with numpy, the sonar image that is formed is a polar image in a rectangular format. This is confusing but it works for most purposes. For better CV image processing of the gate, however, it should be changed to polar format.

The first .75 meters of the sonar scan are also noise so they should be dynamically filtered out.

# Tasks
- [ ] Find 'SERIAL_PORT_NAME' dynamically
- [ ] Find a better system to determine the period and duration
- [ ] Create a polar image processing function in 'sonar_image_processing'
- [ ] Create a dynamically filtering method so the first few points of the sonar are filtered out
- [ ] Prune extraneous code from the sonar such as the rosaction code (once the node works)
- [ ] Make a new custom message for the sonar to communicate to CV and task planning over. 
- [ ] Need to test the 'to_robot_position' function to make sure that the position taken from the polar image is the same as the physical location of the object.
- [ ] Update the 'get_xy_of_object_in_sweep' method to be more robust for finding a small cluster of points (right now it takes the average which is prone to extraneous values).
- [ ] The sonar is currently started called from motion.launch. If the thrusters aren't turned on then the sonar isn't either as it is connected to the thrusters power. Also - there are issues if the thrusters are not turned on before the docker container is made! The docker needs to be able to see the sonar in the port for it to be forwarded to the container. Eventually, the sonar will be connected to the main powerbus without the need to turn on the thruster but for now the code should not error out if the sonar is not available.
  - [ ] In the 'sonar_publishing' file, it should throw an error but not stop the program from running. 
  - [ ] In the same file, whenever the sonar is called and disabled it should return an error message.
  - [ ] All other files which call the sonar should be able to interperet this error
- [ ] Remove the 'test_scan_and_finding_gate_posts' method from the sonar class (move it somewhere else)
- [ ] Remove the 'test_gate_from_npy_file' and 'test_buoy_from_npy_file' methods as well.
- [ ] In sonar image processing, remake the gate finding method to use a more robust system for finding the gate. Currently it detects all "circular" objects by perimeter and the finds the one which is the most concave. This should be switched to a different system which can accurately find the gate.
- [ ] The node system needs to be setup for task-planning to interact with the gate finding method.
- [ ] If task-planning is still in the gate stage, the CV method should not be able to be called until the gate is found as that could cause some errors finding the gate.
- [ ] in 'sonar_image_processing' remove the find_buoy' method (or change it)
- [ ] Add buoy hit detection
- [ ] Fix FOV camera buoy correlation
