### ISSUE TITLE
Spatial Detection Performance Improvements

### ISSUE THREAD

**Issue by vedarshshah** [DukeRobotics/robosub-ros#406]
# Background

Currently, our DepthAI spatial detection pipeline produces detections at 1Hz. The detection rate must be improved for the robot to effectively navigate to the buoys and other targets.

# Purpose

To improve the detection rate of the DepthAI spatial detection pipeline. We wish to get the detection rate to at least 15 Hz and hopefully to 30 Hz.

# Tasks
- [x] Remove the `loop_rate` in `depthai_spatial_detection.py` that artificially limits the detection rate to 1Hz.
- [x] Parametrize all output queues except "detections" so they can be turned off and on by changing values of arguments in the launch file. Set the default to `True` for the "rgb" queue, `False` for all other queues.
- [x] Publish the depth map to a topic if its output queue exists.
- [x] Parametrize the `sync_nn` argument to the `build_pipeline` function so its value is controlled by the launch arguments. Set the default to `True`.
- [x] Benchmark the detection rate after all changes are made above. Obtain two benchmarks: one with the "rgb" output queue turned on (and all other output queues turned off) and one with all output queues (including "rgb") turned off. Both benchmarks must be obtained on the robot.

**Comment by vedarshshah** [comment]
Detection Rates:
With "rgb_raw" and "rgb_detections" turned on: 21 Hz
With all output queues turned off (except detections): 22 Hz
