### ISSUE TITLE
Improve Detection Visualizer

### ISSUE THREAD

**Issue by vedarshshah** [DukeRobotics/robosub-ros#414]
# Background

Currently, the bounding boxes and associated text that is drawn on a live or simulated image feed by `depthai_spatial_detection.py` and `depthai_simulate_detection.py` is always colored white with a black outline. Sometimes this becomes hard to read. Additionally, the fact that the same colors are used for all detected classes means that the only way to find out what class a bounding box belongs to is to read the hard-to-read text.

Therefore, we need to change the visualization of the bounding boxes to include different-colored boxes and to have the labels be easy to read. This can be done in a fashion similar to what is depicted in [this image](https://media.cheggcdn.com/media/6a3/6a31dafb-7fb3-4ddd-a64c-5a78f74ead3d/php90cWP2).

# Purpose

To modify the `DetectionVisualizer` class to draw bounding boxes and text in a way that is easy to read and interpret.

# Tasks

Complete by 4/15.

- [x] In `depthai_models.yaml`, add a key to each model that contains a list of colors, expressed as tuples with three values ranging from 0-255. The color at index `i` in the colors list will be used for the color of the bounding box of class at index `i` in the classes list.
- [x] In the initialization function of `DetectionVisualizer` (located in `utils.py`) remove the properties `self.bg_color` and `self.color`. Add a parameter that is the list of color tuples corresponding to the classes.
- [x] Modify the rest of `DetectionVisualizer` to replace the references to `self.color` with the appropriate color for the colors list.
- [x] Remove lines that draw rectangles or text using `self.bg_color` as we will no longer be outlining the bounding boxes and text.
- [x] In `putText`, add code that adds a solid, filled rectangle behind the text with the appropriate color from the colors list. Make the text always be colored black.
- [x] Modify `depthai_spatial_detection.py` to pass the colors list to DetectionVisualizer when initializing it. Test it to see if the bounding boxes are now colored appropriately, without an outline, with black text, and with a solid, filled, colored rectangle behind the text.
- [x] Modify and test `depthai_simulate_detection.py` like the previous task.
- [x] Reposition the class name so by default it appears above the top left corner of the bounding box, like the example linked above. If the bounding box is too close to the top edge of the image, the class name should instead be positioned below the top left corner, inside the bounding box.
- [x] Remove the separate call to `putText` to add the confidence value. Instead, concatenate the confidence value to the class name so they always appear together.
- [x] Add two boolean arguments to the initialization function of `DetectionVisualizer`. One controls if the class name is displayed, the other controls if the confidence value is displayed. The default value of both arguments should be true (class name and confidence values are displayed).
- [x] Add two launch arguments to each of `depthai_spatial_detection.py` and `depthai_simulate_detection.py` that controls whether the class name and confidence values are displayed.
- [x] Identify six easily distinguishable colors to use as the colors for the classes in our 2023 model.
