### ISSUE TITLE
Restart DepthAI Camera from Camera Status Plugin

### ISSUE THREAD

**Issue by vedarshshah** [DukeRobotics/robosub-ros#416]
# Background

Occasionally, the DepthAI camera becomes unresponsive. It becomes impossible to connect to the camera through code without restarting the camera. The only way to restart the camera is to simply unplug and replug it.

Unplugging and replugging the camera is possible on Cthulhu, since the camera is connected with a SubConn cable. However, this is not possible on Oogway, since the camera is connected with a wetlink penetrator which cannot be physically unplugged without removing the waterproof lid.

To enable us to easily restart the camera on Oogway, the electrical team has added a relay, controlled by the Arduino, that enables us to turn the camera on and off. They have also written the necessary ROS nodes to send commands to the relay to toggle the camera. 

We need to be able to toggle the camera through the camera status plugin.

# Purpose

Add the capability to our camera status plugin to call the appropriate rosservice to turn the DepthAI camera on and off through the relay on Oogway.

# Tasks
Complete everything by 4/12.
- [x] Add a row to the main table in camera status plugin that displays the current status of the relay, as published to the topic.
- [x] Add a tab to the log dialog that displays the log of the relay status.
- [x] Add two buttons buttons that call the service to turn the relay on and off. When the buttons are pressed, show a confirmation dialog before calling the service.
- [x] Modify perspective file to adjust to new size of widget.

**Comment by maxwellmlin** [comment]
Instead of two buttons, I am implementing a single button that toggles the relay to save space.
