### ISSUE TITLE
Fix DepthAI Deprecated Code

### ISSUE THREAD

**Issue by maxwellmlin** [DukeRobotics/robosub-ros#462]
# Background
The following commands are known to be deprecated (there may be more)
```python
mono_left.setBoardSocket(dai.CameraBoardSocket.LEFT)
mono_right.setBoardSocket(dai.CameraBoardSocket.RIGHT)
stereo.setDepthAlign(dai.CameraBoardSocket.RGB)
```

# Purpose
Fix deprecated DepthAI code so that no deprecation warnings show up when running any DepthAI code.

# Tasks
- [x] Update deprecated code in `depthai_spatial_detection.py`.
- [x] Update deprecated code in `depthai_simulate_detection.py`.
- [ ] Test all changes to deprecated code.
